// Meta's supported template language codes (Supported Languages, updated 2026-05-21). The label carries both the name and the code so search matches either.
export const WHATSAPP_TEMPLATE_LANGUAGES = [
  { value: 'af', label: 'Afrikaans - af' },
  { value: 'sq', label: 'Albanian - sq' },
  { value: 'ar', label: 'Arabic - ar' },
  { value: 'ar_EG', label: 'Arabic (EGY) - ar_EG' },
  { value: 'ar_AE', label: 'Arabic (UAE) - ar_AE' },
  { value: 'ar_LB', label: 'Arabic (LBN) - ar_LB' },
  { value: 'ar_MA', label: 'Arabic (MAR) - ar_MA' },
  { value: 'ar_QA', label: 'Arabic (QAT) - ar_QA' },
  { value: 'az', label: 'Azerbaijani - az' },
  { value: 'be_BY', label: 'Belarusian - be_BY' },
  { value: 'bn', label: 'Bengali - bn' },
  { value: 'bn_IN', label: 'Bengali (IND) - bn_IN' },
  { value: 'bg', label: 'Bulgarian - bg' },
  { value: 'ca', label: 'Catalan - ca' },
  { value: 'zh_CN', label: 'Chinese (CHN) - zh_CN' },
  { value: 'zh_HK', label: 'Chinese (HKG) - zh_HK' },
  { value: 'zh_TW', label: 'Chinese (TAI) - zh_TW' },
  { value: 'hr', label: 'Croatian - hr' },
  { value: 'cs', label: 'Czech - cs' },
  { value: 'da', label: 'Danish - da' },
  { value: 'prs_AF', label: 'Dari - prs_AF' },
  { value: 'nl', label: 'Dutch - nl' },
  { value: 'nl_BE', label: 'Dutch (BEL) - nl_BE' },
  { value: 'en', label: 'English - en' },
  { value: 'en_GB', label: 'English (UK) - en_GB' },
  { value: 'en_US', label: 'English (US) - en_US' },
  { value: 'en_AE', label: 'English (UAE) - en_AE' },
  { value: 'en_AU', label: 'English (AUS) - en_AU' },
  { value: 'en_CA', label: 'English (CAN) - en_CA' },
  { value: 'en_GH', label: 'English (GHA) - en_GH' },
  { value: 'en_IE', label: 'English (IRL) - en_IE' },
  { value: 'en_IN', label: 'English (IND) - en_IN' },
  { value: 'en_JM', label: 'English (JAM) - en_JM' },
  { value: 'en_MY', label: 'English (MYS) - en_MY' },
  { value: 'en_NZ', label: 'English (NZL) - en_NZ' },
  { value: 'en_QA', label: 'English (QAT) - en_QA' },
  { value: 'en_SG', label: 'English (SGP) - en_SG' },
  { value: 'en_UG', label: 'English (UGA) - en_UG' },
  { value: 'en_ZA', label: 'English (ZAF) - en_ZA' },
  { value: 'et', label: 'Estonian - et' },
  { value: 'fil', label: 'Filipino - fil' },
  { value: 'fi', label: 'Finnish - fi' },
  { value: 'fr', label: 'French - fr' },
  { value: 'fr_BE', label: 'French (BEL) - fr_BE' },
  { value: 'fr_CA', label: 'French (CAN) - fr_CA' },
  { value: 'fr_CH', label: 'French (CHE) - fr_CH' },
  { value: 'fr_CI', label: 'French (CIV) - fr_CI' },
  { value: 'fr_MA', label: 'French (MAR) - fr_MA' },
  { value: 'ka', label: 'Georgian - ka' },
  { value: 'de', label: 'German - de' },
  { value: 'de_AT', label: 'German (AUT) - de_AT' },
  { value: 'de_CH', label: 'German (CHE) - de_CH' },
  { value: 'el', label: 'Greek - el' },
  { value: 'gu', label: 'Gujarati - gu' },
  { value: 'ha', label: 'Hausa - ha' },
  { value: 'he', label: 'Hebrew - he' },
  { value: 'hi', label: 'Hindi - hi' },
  { value: 'hu', label: 'Hungarian - hu' },
  { value: 'id', label: 'Indonesian - id' },
  { value: 'ga', label: 'Irish - ga' },
  { value: 'it', label: 'Italian - it' },
  { value: 'ja', label: 'Japanese - ja' },
  { value: 'kn', label: 'Kannada - kn' },
  { value: 'kk', label: 'Kazakh - kk' },
  { value: 'rw_RW', label: 'Kinyarwanda - rw_RW' },
  { value: 'ko', label: 'Korean - ko' },
  { value: 'ky_KG', label: 'Kyrgyz (Kyrgyzstan) - ky_KG' },
  { value: 'lo', label: 'Lao - lo' },
  { value: 'lv', label: 'Latvian - lv' },
  { value: 'lt', label: 'Lithuanian - lt' },
  { value: 'mk', label: 'Macedonian - mk' },
  { value: 'ms', label: 'Malay - ms' },
  { value: 'ml', label: 'Malayalam - ml' },
  { value: 'mr', label: 'Marathi - mr' },
  { value: 'nb', label: 'Norwegian - nb' },
  { value: 'ps_AF', label: 'Pashto - ps_AF' },
  { value: 'fa', label: 'Persian - fa' },
  { value: 'pl', label: 'Polish - pl' },
  { value: 'pt_BR', label: 'Portuguese (BR) - pt_BR' },
  { value: 'pt_PT', label: 'Portuguese (POR) - pt_PT' },
  { value: 'pa', label: 'Punjabi - pa' },
  { value: 'ro', label: 'Romanian - ro' },
  { value: 'ru', label: 'Russian - ru' },
  { value: 'sr', label: 'Serbian - sr' },
  { value: 'si_LK', label: 'Sinhala - si_LK' },
  { value: 'sk', label: 'Slovak - sk' },
  { value: 'sl', label: 'Slovenian - sl' },
  { value: 'es', label: 'Spanish - es' },
  { value: 'es_AR', label: 'Spanish (ARG) - es_AR' },
  { value: 'es_CL', label: 'Spanish (CHL) - es_CL' },
  { value: 'es_CO', label: 'Spanish (COL) - es_CO' },
  { value: 'es_CR', label: 'Spanish (CRI) - es_CR' },
  { value: 'es_DO', label: 'Spanish (DOM) - es_DO' },
  { value: 'es_EC', label: 'Spanish (ECU) - es_EC' },
  { value: 'es_HN', label: 'Spanish (HND) - es_HN' },
  { value: 'es_MX', label: 'Spanish (MEX) - es_MX' },
  { value: 'es_PA', label: 'Spanish (PAN) - es_PA' },
  { value: 'es_PE', label: 'Spanish (PER) - es_PE' },
  { value: 'es_ES', label: 'Spanish (SPA) - es_ES' },
  { value: 'es_UY', label: 'Spanish (URY) - es_UY' },
  { value: 'sw', label: 'Swahili - sw' },
  { value: 'sv', label: 'Swedish - sv' },
  { value: 'ta', label: 'Tamil - ta' },
  { value: 'te', label: 'Telugu - te' },
  { value: 'th', label: 'Thai - th' },
  { value: 'tr', label: 'Turkish - tr' },
  { value: 'uk', label: 'Ukrainian - uk' },
  { value: 'ur', label: 'Urdu - ur' },
  { value: 'uz', label: 'Uzbek - uz' },
  { value: 'vi', label: 'Vietnamese - vi' },
  { value: 'zu', label: 'Zulu - zu' }
]
